### PR TITLE
Add parallel build option to setup.py.

### PR DESCRIPTION
**Pull request by skrah**
This enables a parallel build by default in setup.py.

### CODE REVIEW

**Comment by skrah** [comment]
Funny: g++-4.9: internal compiler error: Killed (program cc1plus)

Too bad, it works on my machine.

**Comment by mwiebe** [comment]
That's bizarre, it should work equivalently unless part of the dependencies aren't set up right in the cmakelists

**Comment by insertinterestingnamehere** [comment]
We've had grief with this sort of thing in the CI systems before. The internal compiler errors come because the CI system runs out of memory. Particularly on Travis CI, the reported number of cores is usually much higher than the number of cores actually available, so too many threads get launched, causing the crash.

**Comment by mwiebe** [comment]
So there should probably be a num_threads parameter to setup.py or something to control that on the CI builds.

**Comment by insertinterestingnamehere** [comment]
Yep, an extra argument to setup.py would work. Last time I tried adjusting these parameters it was in the conda recipe for libdynd. Extra parameters aren't available there.

**Comment by izaid** [comment]
@skrah This is totally a CI thing with the machines running out of memory. We've seen it many times before, as Ian said.

**Comment by skrah** [comment]
The latest patch uses ```-jN``` as the setup.py argument. This is already present in Python 3.5, where it has a slightly different meaning (parallel build of multiple extensions), but that is harmless here.

So in Python < 3.5:
  ```python2 setup.py build_ext -j2```

In Python >= 3.5 both happen to work:
  ```python3 setup.py build_ext -j2```
  ```python3 setup.py build -j2```

**Comment by skrah** [comment]
Closing temporarily -- I need a fresh fork and GitHub apparently won't allow this with open PRs.

**Comment by mwiebe** [comment]
@skrah can you explain what you mean by a fresh fork? I've generally found I can get pull requests into a desired state by working locally, then force-pushing to the branch the PR is for.

**Comment by skrah** [comment]
@mwiebe  It's hard to say what went wrong since GitHub itself had severe issues today (totally unreachable for 5 min, then not reacting to any commands for at least two hours: https://status.github.com/messages).

Before I read the above status message, I was unable to update my fork: GitHub claimed that the fork was 8 commits behind on the master branch, but my local clone had all the latest commits. Pushing the master branch *appeared* to work normally but did not have any effect on the web page.

So I tried to get a new fork, but that was impossible as well for about two hours.

I still don't know if it was just GitHub not updating the databases or me messing up a force-push on Sunday.

**Comment by mwiebe** [comment]
Ugh, that's no fun! Hopefully it was all the github problems, and doesn't come back...

**Pull request closed without merging**
