### PR TITLE
pxd restructuring

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This is a partial restructuring of the pxd files that moves toward making the internal declarations used in dynd-python usable in other modules. Further cleanup coming soon.

### CODE REVIEW

**Comment by izaid** [comment]
This generally looks great to me! My only thought is this: Do we want a pxd file even for simple C++ wrapping, like each ndt::*_type. I don't know, probably yes?

Also, @mwiebe, do you want to have a look?

**Comment by insertinterestingnamehere** [comment]
@izaid Thanks for looking through it! There's a little left to do here, but I should be finished later today.

The main reason I structured the pxd files this way is to make it so that someone familiar with the C++ header layout can know where a declaration is without having to look for it anywhere else. It also avoids including unneeded headers. I can make it simpler if we want though. Given how few Cython-level declarations we currently have, that may make sense.

**Comment by insertinterestingnamehere** [comment]
Okay, the more I'm thinking about it, the more I'm thinking that the rest of the changes I was going to do need to be left for later. I had planned to make pxd files that mimic the namespaces as well (by just importing the declarations from the corresponding headers). That seems to be over-complicating it at the moment though. Thoughts?

Also, I was planning to restructure the pydynd external declarations, but that should wait till a different pull request. I think we need to set up all the public functions in the pydynd namespace to be loaded via Python's capsule objects the way numpy does it, rather than using the current rpath-based technique. This should definitively fix all the rpath handling issues we've been having on windows. Once that is done, we can decide whether to include the pydynd declarations in a separate part of the dynd-python module or if the relevant declarations should be included as a part of the existing dynd.nd and dynd.ndt cython declarations.

From here, I think the way forward with these changes is to start adding declarations to the dynd.cpp pxd files while simultaneously doing the following:

- Make all the pydynd shared object's functionality usable for other python modules via Python's capsule objects, and use that mechanism to use these declarations where they are currently needed in the Cython files.
- Determine how/if the pydynd-level functions should be exported to other Python modules
- Make any exported pydynd functions available for use via dynamic loading in Cython.

Once I'm farther along with adding the Cython declarations for interacting with the C++ library, we can re-evaluate whether or not we want pxd files that allow cimporting the declarations for a whole namespace.

What do you think?

**Comment by izaid** [comment]
Okay, I've thought about this a little. I like the idea of using the capsule objects and agree it should be used where necessary (basically all of pydynd). It doesn't sort out the Windows linking issues fully, does it?

In the Cython files, there are calls back to just dynd itself. I think that's a feature we want to maintain, the ability to call dynd functions from Cython.

Anyway, regardless of whether the capsule object solves the Windows issues, I think it is a solid step in the right direction. Do you want me to merge this now so you can get started on that?

**Comment by insertinterestingnamehere** [comment]
Okay, I just updated this with a few more small cleanup items. If the Travis tests pass, this is good to merge.

I just tried using these external declarations from outside dynd-python, and it looks like `pydynd.so` still needs to be included in the rpath for the external module as well. I don't see any other issues, so the next step is to set up pydynd.so as a Python module rather than just a shared library.

Thanks!

**Comment by insertinterestingnamehere** [comment]
Also, I'm fairly sure using Python capsules will sort out the linking issues on Windows. Capsules are the mechanism used in Cython modules and in the NumPy core to export C-level declarations, and both are used extensively on Windows. On a technical level, the capsules can be used to pass pointers to all the needed functions through the Python interpreter to the new module, so linking against any additional library shouldn't even be necessary once we've made the transition to using capsules.

**Pull request merged**
