### PR TITLE
Link dynd.ndt against libdyndt only.

### PR DESCRIPTION
**Pull request by skrah**
Re-opening.  -- Testing on Windows is more involved than I thought: I can't install Visual Studio 14.0 because the installer is broken (on Windows 7):

http://stackoverflow.com/questions/32445763/a-setup-package-is-either-missing-or-damaged-error-while-installing-visual-stu

### CODE REVIEW

**Comment by izaid** [comment]
Pinging @insertinterestingnamehere the Windows wizard to help with this. And @mwiebe.

**Comment by insertinterestingnamehere** [comment]
Taking a look now...

**Comment by insertinterestingnamehere** [comment]
Issues should be addressed in https://github.com/libdynd/dynd-python/pull/691.

**Comment by skrah** [comment]
@insertinterestingnamehere Thanks!   BTW, I've finally managed to install VS 14 (using a fresh install of Windows 10). The Windows build is really excellent, great setup.

**Comment by insertinterestingnamehere** [comment]
Thanks! It's always a relief to hear that it works for other people too.

**Pull request closed without merging**
