### PR TITLE
WIP: Separated the dynd and pydynd namespaces.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
I still need to do whitespace/cosmetic fixes and do another pass through the code to make sure it is all sane, but this should be close to ready.

**Comment by insertinterestingnamehere** [comment]
After trying a few different things, I decided to use a find/replace script to do this. I've posted the script at https://gist.github.com/insertinterestingnamehere/21c77e40c10c4b79821b.

**Comment by insertinterestingnamehere** [comment]
This should be done. I went ahead and applied clang-format version 3.6 to all the c++ sources.
A quick note about the namespace separation. I only made the separation explicit in files where members from dynd::nd and dynd::ndt were being used as if they were a part of pydynd::nd and pydynd::ndt. Other `using namespace ...` statements were all left as they were.

**Comment by insertinterestingnamehere** [comment]
Alright. I just pushed again with some other small whitespace fixes. Builds pending.

**Comment by izaid** [comment]
Looks good, @insertinterestingnamehere! Merged.

**Pull request merged**
