### PR TITLE
Only link config module against libdyndt and not libdynd.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**

### CODE REVIEW

**Comment by skrah** [comment]
I think the broadcast_error needs to be moved somehow, it isn't in libdyndt:

```>>> import dynd.ndt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/clang/lib/python3.6/site-packages/dynd-0.7.3.dev208-py3.6-linux-x86_64.egg/dynd/__init__.py", line 55, in <module>
    from .config import _dynd_version_string as __libdynd_version__, \
ImportError: /home/stefan/clang/lib/python3.6/site-packages/dynd-0.7.3.dev208-py3.6-linux-x86_64.egg/dynd/config.cpython-36-x86_64-linux-gnu.so: undefined symbol: _ZTIN4dynd15broadcast_errorE
```

**Comment by insertinterestingnamehere** [comment]
Right. I saw that error in one of the CI builds. The odd thing is that, if that were the case, I would have expected an error at link time. On top of that, https://github.com/libdynd/libdynd/blob/master/CMakeLists.txt#L250 shows that the relevant source file is already getting built as a part of libdyndt and not libdynd.

**Comment by izaid** [comment]
I've seen that error before when certain things are being loaded correctly -- broadcast_error is one of the first things that it complains about. @skrah You might need to ensure libdynd is in `LD_LIBRARY_PATH`.

**Comment by skrah** [comment]
I got this error while trying to package dynd.ndt with libdyndt.so only.  How about moving the broadcast_error from ```src/dynd/array.cpp``` to ```src/dynd/exceptions.cpp```? It's building here and it is relatively clean -- just one of the convenience overloads of broadcast_error has to go.

**Comment by izaid** [comment]
I'm happy with that, if @insertinterestingnamehere is okay with it.

**Comment by insertinterestingnamehere** [comment]
Yes. That makes a ton of sense. For some reason I was thinking it was already there. We should really be exporting all our exceptions from the same place.

**Comment by skrah** [comment]
Cool, I'll work on a PR.

**Comment by skrah** [comment]
I think with https://github.com/libdynd/libdynd/pull/1241 applied this one should also pass.  With both applied it seems to be possible to package dynd.ndt with libdyndt.so only (yay!).

**Comment by insertinterestingnamehere** [comment]
Great! I'll restart the tests here once the latest conda packages from libdynd are up on our channel. Thanks!

**Pull request merged**
