### PR TITLE
[WIP] Elwise

### PR DESCRIPTION
**Pull request by izaid**

### CODE REVIEW

**Comment by jreback** [comment]
love your new features! 

can u post / send me an example using new
when u have w chance!

**Comment by izaid** [comment]
@jreback Yes, need to email you! Am trying to deal with all the garbage between us and proper comparison operators. :)

**Comment by jreback** [comment]
hahha np

lots of interest on DyND internally so want to sync up with you after your whirlwind 

eg we have the numba guys wanting to integrate with pandas to have GPU support - I am of the opinion that once DyND is integrated this is basically for free (so need to see what makes sense)

**Comment by seibert** [comment]
To add some clarification to @jreback's comment.  We were specifically looking at adding support for AMD's HSA-supporting APUs (GPU and CPU on the same die).  This does not come for free from DyND.  :)

**Comment by izaid** [comment]
@seibert @jreback We need to talk. I just got back to Oxford on the weekend and had a little bit of backlog. I'll send you all an email either today or tomorrow.

**Pull request merged**
