### PR TITLE
Split tests

### PR DESCRIPTION
**Pull request by skrah**
This splits ```dynd.tests``` into ```ndt.test``` and ```nd.test``` directories.  I used ```test``` instead of ```tests``` because I'm looking into making ```python -m ndt.test``` work for executing the tests.

### CODE REVIEW

**Comment by mwiebe** [comment]
The change looks great to me. I'm not a fan of having merges from 'master' into feature branches though, I find the resulting commit histories rather annoying to follow. Could you do a rebase instead?

**Comment by skrah** [comment]
Thanks for taking a look.  -- Yes, rebasing is nicer.  I still sometimes treat git like mercurial, these comments are very helpful (also say if you prefer squashed commits).

**Comment by izaid** [comment]
Ping me when this is ready, and I'll merge.

**Comment by skrah** [comment]
@izaid Yes, this is ready.  Some things will change again when we create the namespace package, but I think that would probably be too much for a single PR.

**Pull request merged**
