### PR TITLE
Update dynd to use nd::array::get_properties().

### PR DESCRIPTION
**Pull request by skrah**
This synchronizes dynd with https://github.com/libdynd/libdynd/pull/970.  (The tests currently segfault here on Linux, but I think they also did before this change.)

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
The crash is specific to clang on Linux and shouldn't show up in the tests here. +1 to the change though.

**Comment by skrah** [comment]
I'm probably stating nothing new here, but the segfault can be turned into a runtime error by uncommenting:

  https://github.com/libdynd/libdynd/blob/master/src/dynd/func/assignment.cpp#L118

Prior to the segfault dst_tp.get_id()==bool and  src_tp[0].get_id())==59, so the lookup fails.

I wonder if clang is too aggressive with casting ints to enums, which may be undefined behavior:

  https://www.securecoding.cert.org/confluence/display/cplusplus/INT50-CPP.+Do+not+cast+to+an+out-of-range+enumeration+value

**Comment by izaid** [comment]
@skrah Interesting. @insertinterestingnamehere and I stepped through this bug as well, and you are right at what is going on. However, everything should work, and we think this is a linking issue due to Ian's recent changes in DyND Python. The type ID of 59 is a dynamic type ID and there should be a callable in the assignment table for it.

**Comment by mwiebe** [comment]
That crash only happens in release mode, if I do -DCMAKE_BUILD_TYPE=Debug, the tests run fine.

**Comment by skrah** [comment]
@izaid My enum hypothesis can be ruled out: The crash also occurs with:

```diff --git a/include/dynd/types/type_id.hpp b/include/dynd/types/type_id.hpp
index 2427e29..c6f0cf2 100644
--- a/include/dynd/types/type_id.hpp
+++ b/include/dynd/types/type_id.hpp
@@ -18,7 +18,7 @@ namespace ndt {
   class type;
 }
 
-enum type_kind_t {
+enum type_kind_t : size_t {
   bool_kind,
   uint_kind,
   sint_kind,
@@ -66,7 +66,7 @@ enum type_kind_t {
   custom_kind
 };
 
-enum type_id_t {
+enum type_id_t : size_t {
   // The value zero is reserved for an uninitialized type.
   uninitialized_id,
```

**Pull request merged**
