### PR TITLE
Fix DLL preload for the libdynd default install location.

### PR DESCRIPTION
**Pull request by skrah**
This fixes the dll preload if libdynd is installed in ```Program Files```.

Two more things:

    1) I tried to remove the ImportError from dynd\___init__.py. This is surprisingly
        tricky if you want to have the same dynd\__init__.py file for both dynd.ndt
        and dynd.nd.  Having the same file is easier logistically.

    2) I removed the namespace cleanups "del common" etc. since some of those
        were not robust.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
Thanks! This looks right to me. Is this good to merge?

**Comment by skrah** [comment]
Yes, this should be good.

**Comment by insertinterestingnamehere** [comment]
Okay, I see a similar commit in https://github.com/libdynd/dynd-python/pull/712 is this going to throw that PR off at all?

**Comment by skrah** [comment]
No, #712  is branched off this. You can either merge that and close this one or I update the master after this is merged.

**Comment by insertinterestingnamehere** [comment]
Got it. I'll just review that one now.

**Comment by insertinterestingnamehere** [comment]
Merged as a part of https://github.com/libdynd/dynd-python/pull/712.

**Pull request closed without merging**
