### PR TITLE
Link dynd.ndt against libdyndt only.

### PR DESCRIPTION
**Pull request by skrah**
This is the same as https://github.com/libdynd/dynd-python/pull/670 with a clean history.

### CODE REVIEW

**Comment by izaid** [comment]
Great! FYI, anaconda.org is currently throwing some 404 errors, so any builds that depend on conda are currently failing sometimes -- nothing to do with DyND.

**Comment by skrah** [comment]
Okay, Linux and OS X are fine.  Windows still has a link error -- I'll have to set up Windows VM to debug that.

**Comment by izaid** [comment]
Yeah, have a look. If Windows needs a piece of `nd::array`, let me know and we can talk about how to sort that out.

**Comment by izaid** [comment]
@skrah Sorry, I hit merge on this accidentally, but it's been reverted. You'll have to reopen.

**Pull request merged**
