### PR TITLE
Link dynd.ndt against libdyndt only.

### PR DESCRIPTION
**Pull request by skrah**
This drops the libdynd linkage dependency from the build.

### CODE REVIEW

**Comment by izaid** [comment]
This will be really great when it passes!

**Comment by skrah** [comment]
With https://github.com/libdynd/libdynd/pull/1200 committed and using an installed libdyndt.so the build and the tests pass here on Linux.

$ ldd type.cpython-36-x86_64-linux-gnu.so
        linux-vdso.so.1 =>  (0x00007fffaa1fe000)
        libpython3.6.so.1.0 => not found
        libdyndt.so => /usr/local/lib/libdyndt.so (0x00007f7e3236d000)
        libc++.so.1 => /usr/lib/x86_64-linux-gnu/libc++.so.1 (0x00007f7e3207a000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7e31d74000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7e31b5e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7e31798000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7e3157a000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7e31372000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7e3295d000)

**Comment by izaid** [comment]
@skrah Can you update this and let me know if it is ready to go?

**Comment by skrah** [comment]
Superseded by https://github.com/libdynd/dynd-python/pull/674 .

**Pull request closed without merging**
