### PR TITLE
Separate library for c++ functions

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**
This still doesn't quite work. I have more linker errors to fix as it stands. The end-goal is to make it so that Cython extensions don't need to link against anything for these functions, but compiling them as a separate library is a good first step toward making that happen.

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
@mwiebe @izaid I've run into a few compile errors that I don't recognize. I'd appreciate your help here. Also, in the long run, depending on how we want the C++ API to look, it may make more sense to try to model the exporting of the functions after what NumPy does (and the Python docs recommend) rather than going through all this hassle to get everything into a separate shared object without meaning to use it in the end. What are your thoughts?

**Comment by izaid** [comment]
@insertinterestingnamehere If you can wait until tomorrow, I'll give this a proper try!

**Comment by insertinterestingnamehere** [comment]
If we need to, I can try breaking up the Cython pxd files so that linking against the original shared object isn't necessary from the Cython side. That should provide a workaround for experimentation until we get the C++ API figured out a little better.

**Comment by izaid** [comment]
@insertinterestingnamehere Okay, so I've just tried your branch. On my Mac, I get different errors -- basically, all of pydynd is undefined.

What do you think about the following? I wouldn't mind doing a bit of refactoring on dynd-python. I can do this now, if you are happy working on the Cython bugs we talked about. Is that alright?

**Comment by insertinterestingnamehere** [comment]
That sounds great to me. Thanks for looking at it!

**Comment by izaid** [comment]
@insertinterestingnamehere Okay if I close this? We achieved this in another PR.

**Comment by insertinterestingnamehere** [comment]
Sounds good. Thanks!
Closing.

**Pull request closed without merging**
