### PR TITLE
Allow proper overriding of CXXFLAGS.

### PR DESCRIPTION
**Pull request by skrah**
This allows CXXFLAGS in the environment to override the official cmake flags. 

@insertinterestingnamehere Would you want this for Windows, too? I didn't want to touch that.

### CODE REVIEW

**Comment by izaid** [comment]
Why do we need `DYND_CXX_FLAGS`? What's wrong with just doing `-DCMAKE_CXX_FLAGS=...`?

**Comment by skrah** [comment]
I'm not sure . Can this somehow be done with "python setup.py develop"?

**Comment by skrah** [comment]
```-DCMAKE_CXX_FLAGS="-O0 -g"``` also doesn't allow the compiler to pick up the flags, since they're prepended:

   ```/usr/bin/clang++   -DPYDYND_EXPORT -Ddynd_config_EXPORTS -O0 -g -g -fomit-frame-pointer```

The flags need to be appended for overriding (last flag wins).

**Comment by izaid** [comment]
Okay, so here's the solution we've arrived at before. DyND Python's setup.py actually takes `-extra_cmake_args="..."`, see https://github.com/libdynd/dynd-python/blob/master/setup.py#L111. YOu can pass anything you like in there.

If we need to change CMAKE_CXX_FLAGS so that things are being appended, that's cool and we should do that.

Will the combination of `-extra_cmake_args` and changing CMAKE_CXX_FLAGS give you everything you need?

**Comment by mwiebe** [comment]
Would be nice to fix up the Windows flags while you're at it too. Instead of introducing DYND_CXX_FLAGS, could maybe just always prepend new flags whenever some are added?

**Comment by insertinterestingnamehere** [comment]
Yep, +1 to using CMAKE_CXX_FLAGS. The way it's currently set up we already prepend user-specified flags to the ones we use. Should be be prepending them or appending them?

**Comment by mwiebe** [comment]
I was thinking prepend our flags to the already existing CMAKE_CXX_FLAGS. That would be append user-specified flags to ours. :)

**Comment by insertinterestingnamehere** [comment]
That sounds great to me. My main worry is that `-Wno-(whatever error)` specified by the user should preclude our use of `-Wall`. I *think* prepending our flags would do that. (checking now...)

**Comment by mwiebe** [comment]
I think we should allow the user to control things like that via appended flags. Otherwise it's like how some websites try to disable copy/paste...

**Comment by insertinterestingnamehere** [comment]
Okay, it looks like, at least with gcc, the flags that disable warnings always take precedence over things like `-Wall -Wextra` regardless of the actual order. So... I don't really have any preference since either way makes things user-specifiable.

**Comment by insertinterestingnamehere** [comment]
For explicitly enabled warning, the last flag takes precedence, so prepending our flags to `CMAKE_CXX_FLAGS` is probably the way to go.

**Comment by skrah** [comment]
@izaid Yes, the user ```CMAKE_CXX_FLAGS``` must be last to solve the issue. The fact that this also solves the ```CXXFLAGS ``` issue is just an additional benefit.

@mwiebe The new patch uses prepending, but I also moved the blocks around so that the existing flag order is the same as before.  Avoiding this was the main reason for introducing ```DYND_CXX_FLAGS```.

**Comment by izaid** [comment]
@skrah Is this good to go?

**Comment by skrah** [comment]
@izaid Yes, I think so.

**Comment by izaid** [comment]
LGTM.

**Pull request merged**
