### PR TITLE
Port conversions from python objects to ndt::types to Cython.

### PR DESCRIPTION
**Pull request by insertinterestingnamehere**

### CODE REVIEW

**Comment by insertinterestingnamehere** [comment]
I just got the type constructor to work. I still need to finish cutting out the old `make__type_from_pyobject` stuff fully. This still depends on some pieces of the numpy and ctypes interop, but hopefully those should come out soon enough.

On a more general level, at some point we should make the conversion from Python object to `ndt.type` behave more like a registry. That'll involve setting up some kind of general mapping that can be filled dynamically with the necessary conversions. That's not trivial to set up, so I'm leaving it for later.

**Comment by insertinterestingnamehere** [comment]
@izaid This should be good to go. I didn't remove the old `make__type_from_pyobject` functions since the machinery for using Cython declarations all over the place in the C++ code is still underdeveloped, but this provides working replacements for those functions in Cython.

**Comment by insertinterestingnamehere** [comment]
I'd love to replace the many if blocks with another dynamic registry, but I'm not sure when/how to do that yet.

**Comment by izaid** [comment]
@insertinterestingnamehere Great, just read through it, thanks! I think is a good step forward, so I'm just going to merge it, with the understanding we still have work to do on mapping Python types to DyND types.

**Pull request merged**
